import { defineObject, FieldType } from 'twenty-sdk/define';

import {
  FIELD_ACCESS_TOKEN_UNIVERSAL_IDENTIFIER,
  FIELD_AD_ACCOUNT_IDS_UNIVERSAL_IDENTIFIER,
  FIELD_BUSINESS_ID_UNIVERSAL_IDENTIFIER,
  FIELD_BUSINESS_NAME_UNIVERSAL_IDENTIFIER,
  FIELD_NAME_UNIVERSAL_IDENTIFIER,
  FIELD_PAGE_IDS_UNIVERSAL_IDENTIFIER,
  FIELD_PHONE_NUMBER_ID_UNIVERSAL_IDENTIFIER,
  FIELD_PHONE_NUMBER_UNIVERSAL_IDENTIFIER,
  FIELD_STATUS_UNIVERSAL_IDENTIFIER,
  FIELD_WABA_ID_UNIVERSAL_IDENTIFIER,
  WHATSAPP_CONNECTION_OBJECT_UNIVERSAL_IDENTIFIER,
} from 'src/constants/universal-identifiers';

enum WhatsAppConnectionStatus {
  CONNECTED    = 'CONNECTED',
  DISCONNECTED = 'DISCONNECTED',
  PENDING      = 'PENDING',
}

export default defineObject({
  universalIdentifier: WHATSAPP_CONNECTION_OBJECT_UNIVERSAL_IDENTIFIER,
  nameSingular: 'whatsappConnection',
  namePlural: 'whatsappConnections',
  labelSingular: 'WhatsApp Connection',
  labelPlural: 'WhatsApp Connections',
  description: 'A connected WhatsApp Business Account (WABA)',
  icon: 'IconBrandWhatsapp',
  fields: [
    {
      universalIdentifier: FIELD_NAME_UNIVERSAL_IDENTIFIER,
      name: 'name',
      type: FieldType.TEXT,
      label: 'Name',
      description: 'Display name — auto-set to "BusinessName — WABA ID"',
      icon: 'IconAbc',
    },
    {
      universalIdentifier: FIELD_WABA_ID_UNIVERSAL_IDENTIFIER,
      name: 'wabaId',
      type: FieldType.TEXT,
      label: 'WABA ID',
      description: 'WhatsApp Business Account ID from Meta',
      icon: 'IconHash',
    },
    {
      universalIdentifier: FIELD_PHONE_NUMBER_ID_UNIVERSAL_IDENTIFIER,
      name: 'phoneNumberId',
      type: FieldType.TEXT,
      label: 'Phone Number ID',
      description: "Meta's internal phone number identifier",
      icon: 'IconHash',
    },
    {
      universalIdentifier: FIELD_PHONE_NUMBER_UNIVERSAL_IDENTIFIER,
      name: 'phoneNumber',
      type: FieldType.TEXT,
      label: 'Phone Number',
      description: 'Display phone number (e.g. +1 234 567 8901)',
      icon: 'IconPhone',
    },
    {
      universalIdentifier: FIELD_BUSINESS_ID_UNIVERSAL_IDENTIFIER,
      name: 'businessId',
      type: FieldType.TEXT,
      label: 'Business ID',
      description: 'Meta Business ID',
      icon: 'IconBuilding',
    },
    {
      universalIdentifier: FIELD_BUSINESS_NAME_UNIVERSAL_IDENTIFIER,
      name: 'businessName',
      type: FieldType.TEXT,
      label: 'Business Name',
      description: 'Business display name from Meta',
      icon: 'IconBuilding',
    },
    {
      universalIdentifier: FIELD_ACCESS_TOKEN_UNIVERSAL_IDENTIFIER,
      name: 'accessToken',
      type: FieldType.TEXT,
      label: 'Access Token',
      description: 'Meta access token — treat as sensitive',
      icon: 'IconKey',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: FIELD_AD_ACCOUNT_IDS_UNIVERSAL_IDENTIFIER,
      name: 'adAccountIds',
      type: FieldType.TEXT,
      label: 'Ad Account IDs',
      description: 'JSON array of Meta ad account IDs',
      icon: 'IconAd',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: FIELD_PAGE_IDS_UNIVERSAL_IDENTIFIER,
      name: 'pageIds',
      type: FieldType.TEXT,
      label: 'Page IDs',
      description: 'JSON array of Facebook page IDs',
      icon: 'IconBrandFacebook',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: FIELD_STATUS_UNIVERSAL_IDENTIFIER,
      name: 'status',
      type: FieldType.SELECT,
      label: 'Status',
      description: 'Connection status',
      icon: 'IconCircleDot',
      defaultValue: `'${WhatsAppConnectionStatus.PENDING}'`,
      options: [
        { value: WhatsAppConnectionStatus.CONNECTED,    label: 'Connected',    position: 0, color: 'green'  },
        { value: WhatsAppConnectionStatus.PENDING,      label: 'Pending',      position: 1, color: 'yellow' },
        { value: WhatsAppConnectionStatus.DISCONNECTED, label: 'Disconnected', position: 2, color: 'red'    },
      ],
    },
  ],
});
